package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JToggleButton;
import model.GameOfLife;

/**
 *
 * @author tadaki
 */
public class GOLMain extends javax.swing.JFrame {
    
    private final DrawPanel drawPanel;
    private final JToggleButton toggle;
    private final GameOfLife gol;
    private final int n = 128;
    private boolean running = false;
    
    public enum InitialState {
        Random;
    }
    private final InitialState initState = InitialState.Random;

    /**
     * Creates new form GOLMain
     */
    public GOLMain() {
        initComponents();
        drawPanel = new DrawPanel();
        drawPanel.setPreferredSize(new Dimension(1000, 1000));
        drawPanel.setBackground(Color.white);
        drawPanel.setForeground(Color.red);
        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);
        pack();
        drawPanel.initializePanel();
        gol = new GameOfLife(n);
        drawPanel.setGameOfLife(gol);
        toggle = new JToggleButton("START");
        toggle.setSelected(false);
        toggle.addActionListener(l -> {
            toggleAction();
        });
        menuBar.add(toggle);
    }
    
    private void toggleAction(){
        if (running){
                toggle.setText("START");
                drawPanel.stop();
                running=false;
            } else {
                toggle.setText("STOP");
                setInitialState();
                new Thread(drawPanel).start();
                drawPanel.start();
                running=true;
            }
        toggle.setSelected(false);
    }
    private void setInitialState() {
        switch (initState) {
            default ->
                gol.randomInitialize(0.5);
        }
        drawPanel.clearImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveImage = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        saveImage.setText("SaveImage");
        saveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveImageActionPerformed(evt);
            }
        });
        fileMenu.add(saveImage);

        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        fileMenu.add(quit);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void saveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveImageActionPerformed
        drawPanel.stop();
        toggleAction();
        try {
            drawPanel.saveImage("snapShot.png");
        } catch (IOException ex) {
            Logger.getLogger(GOLMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GOLMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem quit;
    private javax.swing.JMenuItem saveImage;
    // End of variables declaration//GEN-END:variables
}
