package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.GameOfLife;

/**
 *
 * @author tadaki
 */
public class GOLMain extends javax.swing.JFrame {

    private final DrawPanel drawPanel;
    private final GameOfLife gol;
    private final int n=128;

    public enum InitialState {
        Random;
    }
    private final InitialState initState = InitialState.Random;

    /**
     * Creates new form GOLMain
     */
    public GOLMain() {
        initComponents();
        drawPanel = new DrawPanel();
        drawPanel.setPreferredSize(new Dimension(1000, 1000));
        drawPanel.setBackground(Color.white);
        drawPanel.setForeground(Color.red);
        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);
        pack();
        drawPanel.initializePanel();
        gol=new GameOfLife(n);
        drawPanel.setGameOfLife(gol);
    }

    private void setInitialState(){
        switch(initState){
            default -> gol.randomInitialize(0.5);
        }
        drawPanel.clearImage();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        quit = new javax.swing.JButton();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        saveImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttons.setBackground(new java.awt.Color(204, 255, 255));

        quit.setBackground(new java.awt.Color(204, 204, 255));
        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        buttons.add(quit);

        start.setBackground(new java.awt.Color(204, 204, 255));
        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        buttons.add(start);

        stop.setBackground(new java.awt.Color(204, 204, 255));
        stop.setText("STOP");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        buttons.add(stop);

        saveImage.setBackground(new java.awt.Color(204, 204, 255));
        saveImage.setText("SaveImage");
        saveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveImageActionPerformed(evt);
            }
        });
        buttons.add(saveImage);

        getContentPane().add(buttons, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        setInitialState();
        new Thread(drawPanel).start();
        drawPanel.start();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        drawPanel.stop();
    }//GEN-LAST:event_stopActionPerformed

    private void saveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveImageActionPerformed
        drawPanel.stop();
        try {
            drawPanel.saveImage("snapShot.png");
        } catch (IOException ex) {
            Logger.getLogger(GOLMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GOLMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GOLMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JButton quit;
    private javax.swing.JButton saveImage;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
